# Generated by Django 2.0.8 on 2018-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='salt',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
