# Generated by Django 2.0.8 on 2018-09-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet_app', '0002_snippet_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='salt',
        ),
    ]
